//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB_CargoServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CARGO
    {
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> FEE { get; set; }
        [Key]
        public decimal TRACKING_NO { get; set; }
        public System.DateTime SENT_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal STATUS_ID { get; set; }
        public decimal SENDER_ID { get; set; }
    
        public virtual CARGO_STATUS CARGO_STATUS { get; set; }
        public virtual SENDER SENDER { get; set; }
    }
}
