//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB_CargoServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AB_CargoEntities : DbContext
    {
        public AB_CargoEntities()
            : base("name=AB_CargoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOes { get; set; }
        public virtual DbSet<CARGO_STATUS> CARGO_STATUS { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<RECEIVER> RECEIVERs { get; set; }
        public virtual DbSet<SENDER> SENDERs { get; set; }
        public virtual DbSet<SUBSCRIBER> SUBSCRIBERS { get; set; }
        public virtual DbSet<USER_MESSAGES> USER_MESSAGES { get; set; }
        public virtual DbSet<GET_CITIES> GET_CITIES { get; set; }
    }
}
