//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB_CargoServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RECEIVER
    {
        public string FIRST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public decimal SENDER_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string CITY { get; set; }
        [Key]
        public decimal RECEIVER_ID { get; set; }
    
        public virtual SENDER SENDER { get; set; }
    }
}
