//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB_CargoServices.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER_MESSAGES
    {
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime SENT { get; set; }
        [Key]
        public decimal ID { get; set; }
    }
}
